name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GH_CRED_A: ${{ secrets.GH_CRED_A }}
      GH_CRED_B: ${{ secrets.GH_CRED_B }}
      GH_TOKEN: ${{ secrets.GH_CRED_B }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 1mnt/nomnt
          token: ${{ secrets.GH_CRED_B }}

      - name: Connect Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          hostname: xxx
          tags: tag:ci
          args: --ssh

      - name: Download assets
        run: |
          bash ./install.sh

      - name: Await Completion
        run: |
          while true; do sleep 300; done
